### ISSUE TITLE
Call done(err)

### ISSUE THREAD

**Issue by Eomm** [manju4ever/fastify-impressions#1]
In case of error, you need to call the `done` callback or the request flow will be blocked till the timeout.

https://github.com/manju4ever/fastify-impressions/blob/67edec149e9b68fdbb0e8b2fc69836a8cf4723c1/index.js#L54

**Comment by manju4ever** [comment]
Thank you so much @Eomm , i'll get started on it right away.

**Comment by manju4ever** [comment]
Fix pushed to `1.0.4`
