### ISSUE TITLE
Prefer a Map

### ISSUE THREAD

**Issue by Eomm** [manju4ever/fastify-impressions#2]
The complexity for `indexOf` is `O(n)`, but for a `Map.has()` is `O(1)`.
So the more URL will be hit, the more this plugin will slow down

https://github.com/manju4ever/fastify-impressions/blob/67edec149e9b68fdbb0e8b2fc69836a8cf4723c1/index.js#L12

**Comment by manju4ever** [comment]
Makes sense.

**Comment by manju4ever** [comment]
Fix pushed to `1.0.4`
